export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const CREATE_FENCE_START = "CREATE_FENCE_START";
export const CREATE_FENCE_SUCCESS = "CREATE_FENCE_SUCCESS";
export const CREATE_FENCE_FAIL = "CREATE_FENCE_FAIL";

export const GET_FENCES_START = "GET_FENCES_START";
export const GET_FENCES_SUCCESS = "GET_FENCES_SUCCESS";
export const GET_FENCES_FAIL = "GET_FENCES_FAIL";

export const GET_USERS_BY_DEPT_SUCCESS = "GET_USERS_BY_DEPT_SUCCESS";
export const GET_USERS_BY_DEPT_FAIL = "GET_USERS_BY_DEPT_FAIL";

export const GET_USERS_BY_NAMES_SUCCESS = "GET_USERS_BY_NAMES_SUCCESS";
export const GET_USERS_BY_NAMES_FAIL = "GET_USERS_BY_NAMES_FAIL";

export const ASSIGN_USER_START = "ASSIGN_USER_START";
export const ASSIGN_USER_SUCCESS = "ASSIGN_USER_SUCCESS";
export const ASSIGN_USER_FAIL = "ASSIGN_USER_FAIL";

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_ACTIVE_USERS_SUCCESS = "GET_ACTIVE_USERS_SUCCESS";
export const GET_ACTIVE_USERS_FAIL = "GET_ACTIVE_USERS_FAIL";
